//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfPorkProcessSystem.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfPorkProcessSystem.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Este é um projeto de teste simples em C# WPF..
        /// </summary>
        public static string App_Description1 {
            get {
                return ResourceManager.GetString("App_Description1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a É uma POC para uma aplicação web completa.
        /// </summary>
        public static string App_Description2 {
            get {
                return ResourceManager.GetString("App_Description2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O objetivo é testar um sistema de controle de gestão de abate industrial,.
        /// </summary>
        public static string App_Description3 {
            get {
                return ResourceManager.GetString("App_Description3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Para suínos e bovinos..
        /// </summary>
        public static string App_Description4 {
            get {
                return ResourceManager.GetString("App_Description4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Gestão de Carcaças e Estoque de Câmaras.
        /// </summary>
        public static string App_Subtitle {
            get {
                return ResourceManager.GetString("App_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a KFM - Gestão de Abate.
        /// </summary>
        public static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cancelar.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Limpar.
        /// </summary>
        public static string Button_Clear {
            get {
                return ResourceManager.GetString("Button_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Limpar Simulação.
        /// </summary>
        public static string Button_ClearSimulation {
            get {
                return ResourceManager.GetString("Button_ClearSimulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fechar.
        /// </summary>
        public static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Excluir.
        /// </summary>
        public static string Button_Delete {
            get {
                return ResourceManager.GetString("Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Editar.
        /// </summary>
        public static string Button_Edit {
            get {
                return ResourceManager.GetString("Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Carregar.
        /// </summary>
        public static string Button_Load {
            get {
                return ResourceManager.GetString("Button_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Carregar Ordem.
        /// </summary>
        public static string Button_LoadOrder {
            get {
                return ResourceManager.GetString("Button_LoadOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Carregar Relatório.
        /// </summary>
        public static string Button_LoadReport {
            get {
                return ResourceManager.GetString("Button_LoadReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Novo.
        /// </summary>
        public static string Button_New {
            get {
                return ResourceManager.GetString("Button_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pausar.
        /// </summary>
        public static string Button_Pause {
            get {
                return ResourceManager.GetString("Button_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Retomar.
        /// </summary>
        public static string Button_Resume {
            get {
                return ResourceManager.GetString("Button_Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Salvar.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Salvar Configuração.
        /// </summary>
        public static string Button_SaveConfig {
            get {
                return ResourceManager.GetString("Button_SaveConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Iniciar.
        /// </summary>
        public static string Button_Start {
            get {
                return ResourceManager.GetString("Button_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Parar.
        /// </summary>
        public static string Button_Stop {
            get {
                return ResourceManager.GetString("Button_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Classificações Aceitas.
        /// </summary>
        public static string Column_AcceptClassifications {
            get {
                return ResourceManager.GetString("Column_AcceptClassifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Lote.
        /// </summary>
        public static string Column_Batch {
            get {
                return ResourceManager.GetString("Column_Batch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Capacidade.
        /// </summary>
        public static string Column_Capacity {
            get {
                return ResourceManager.GetString("Column_Capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Câmara.
        /// </summary>
        public static string Column_Chamber {
            get {
                return ResourceManager.GetString("Column_Chamber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Classificação.
        /// </summary>
        public static string Column_Classification {
            get {
                return ResourceManager.GetString("Column_Classification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data de Execução.
        /// </summary>
        public static string Column_ExecutionDate {
            get {
                return ResourceManager.GetString("Column_ExecutionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data de Validade.
        /// </summary>
        public static string Column_ExpirationDate {
            get {
                return ResourceManager.GetString("Column_ExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Martelo.
        /// </summary>
        public static string Column_Hammer {
            get {
                return ResourceManager.GetString("Column_Hammer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ID da Nota.
        /// </summary>
        public static string Column_NoteId {
            get {
                return ResourceManager.GetString("Column_NoteId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ID da Ordem.
        /// </summary>
        public static string Column_OrderId {
            get {
                return ResourceManager.GetString("Column_OrderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Produto.
        /// </summary>
        public static string Column_Product {
            get {
                return ResourceManager.GetString("Column_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sequencial.
        /// </summary>
        public static string Column_Sequential {
            get {
                return ResourceManager.GetString("Column_Sequential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Turno.
        /// </summary>
        public static string Column_Shift {
            get {
                return ResourceManager.GetString("Column_Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Estoque.
        /// </summary>
        public static string Column_Stock {
            get {
                return ResourceManager.GetString("Column_Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Peso (kg).
        /// </summary>
        public static string Column_Weight {
            get {
                return ResourceManager.GetString("Column_Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Confirmação.
        /// </summary>
        public static string Dialog_Confirmation {
            get {
                return ResourceManager.GetString("Dialog_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro.
        /// </summary>
        public static string Dialog_Error {
            get {
                return ResourceManager.GetString("Dialog_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Informação.
        /// </summary>
        public static string Dialog_Information {
            get {
                return ResourceManager.GetString("Dialog_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sucesso.
        /// </summary>
        public static string Dialog_Success {
            get {
                return ResourceManager.GetString("Dialog_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Validação.
        /// </summary>
        public static string Dialog_Validation {
            get {
                return ResourceManager.GetString("Dialog_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Aviso.
        /// </summary>
        public static string Dialog_Warning {
            get {
                return ResourceManager.GetString("Dialog_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Classificações Aceitas.
        /// </summary>
        public static string Label_AcceptClassifications {
            get {
                return ResourceManager.GetString("Label_AcceptClassifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Lote.
        /// </summary>
        public static string Label_Batch {
            get {
                return ResourceManager.GetString("Label_Batch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Capacidade.
        /// </summary>
        public static string Label_Capacity {
            get {
                return ResourceManager.GetString("Label_Capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Câmara.
        /// </summary>
        public static string Label_Chamber {
            get {
                return ResourceManager.GetString("Label_Chamber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Classificação.
        /// </summary>
        public static string Label_Classification {
            get {
                return ResourceManager.GetString("Label_Classification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Atraso.
        /// </summary>
        public static string Label_Delay {
            get {
                return ResourceManager.GetString("Label_Delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Descrição.
        /// </summary>
        public static string Label_Description {
            get {
                return ResourceManager.GetString("Label_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ordem de Entrada.
        /// </summary>
        public static string Label_EntranceOrder {
            get {
                return ResourceManager.GetString("Label_EntranceOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data de Execução.
        /// </summary>
        public static string Label_ExecutionDate {
            get {
                return ResourceManager.GetString("Label_ExecutionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data de Validade.
        /// </summary>
        public static string Label_ExpirationDate {
            get {
                return ResourceManager.GetString("Label_ExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data de Faturamento.
        /// </summary>
        public static string Label_FacturingDate {
            get {
                return ResourceManager.GetString("Label_FacturingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Quantidade a Gerar.
        /// </summary>
        public static string Label_GenerateQuantity {
            get {
                return ResourceManager.GetString("Label_GenerateQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Martelo.
        /// </summary>
        public static string Label_Hammer {
            get {
                return ResourceManager.GetString("Label_Hammer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ID.
        /// </summary>
        public static string Label_Id {
            get {
                return ResourceManager.GetString("Label_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Limite Inferior.
        /// </summary>
        public static string Label_LowerLimit {
            get {
                return ResourceManager.GetString("Label_LowerLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome.
        /// </summary>
        public static string Label_Name {
            get {
                return ResourceManager.GetString("Label_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ID da Nota.
        /// </summary>
        public static string Label_NoteId {
            get {
                return ResourceManager.GetString("Label_NoteId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ID da Ordem.
        /// </summary>
        public static string Label_OrderId {
            get {
                return ResourceManager.GetString("Label_OrderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Produto.
        /// </summary>
        public static string Label_Product {
            get {
                return ResourceManager.GetString("Label_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ordem de Produção.
        /// </summary>
        public static string Label_ProductionOrder {
            get {
                return ResourceManager.GetString("Label_ProductionOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Quantidade de Carcaças.
        /// </summary>
        public static string Label_QuantityCarcasses {
            get {
                return ResourceManager.GetString("Label_QuantityCarcasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sequencial.
        /// </summary>
        public static string Label_Sequential {
            get {
                return ResourceManager.GetString("Label_Sequential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Turno.
        /// </summary>
        public static string Label_Shift {
            get {
                return ResourceManager.GetString("Label_Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Câmara de Aspersão.
        /// </summary>
        public static string Label_SprayChamber {
            get {
                return ResourceManager.GetString("Label_SprayChamber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Status.
        /// </summary>
        public static string Label_Status {
            get {
                return ResourceManager.GetString("Label_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Estoque.
        /// </summary>
        public static string Label_Stock {
            get {
                return ResourceManager.GetString("Label_Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Total de Itens.
        /// </summary>
        public static string Label_TotalItems {
            get {
                return ResourceManager.GetString("Label_TotalItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Peso Total.
        /// </summary>
        public static string Label_TotalWeight {
            get {
                return ResourceManager.GetString("Label_TotalWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tipo.
        /// </summary>
        public static string Label_Type {
            get {
                return ResourceManager.GetString("Label_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Limite Superior.
        /// </summary>
        public static string Label_UpperLimit {
            get {
                return ResourceManager.GetString("Label_UpperLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Balança.
        /// </summary>
        public static string Label_WeighingScale {
            get {
                return ResourceManager.GetString("Label_WeighingScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Peso.
        /// </summary>
        public static string Label_Weight {
            get {
                return ResourceManager.GetString("Label_Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Status da Câmara.
        /// </summary>
        public static string Menu_ChamberStatus {
            get {
                return ResourceManager.GetString("Menu_ChamberStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Classificação de Pesagem.
        /// </summary>
        public static string Menu_ClassificationWeighing {
            get {
                return ResourceManager.GetString("Menu_ClassificationWeighing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Formulários.
        /// </summary>
        public static string Menu_Forms {
            get {
                return ResourceManager.GetString("Menu_Forms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Idioma.
        /// </summary>
        public static string Menu_Language {
            get {
                return ResourceManager.GetString("Menu_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Operação.
        /// </summary>
        public static string Menu_Operation {
            get {
                return ResourceManager.GetString("Menu_Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Produto.
        /// </summary>
        public static string Menu_Product {
            get {
                return ResourceManager.GetString("Menu_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Produção.
        /// </summary>
        public static string Menu_Production {
            get {
                return ResourceManager.GetString("Menu_Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ordem de Produção.
        /// </summary>
        public static string Menu_ProductionOrder {
            get {
                return ResourceManager.GetString("Menu_ProductionOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Relatórios.
        /// </summary>
        public static string Menu_Reports {
            get {
                return ResourceManager.GetString("Menu_Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Simulador.
        /// </summary>
        public static string Menu_Simulator {
            get {
                return ResourceManager.GetString("Menu_Simulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Câmaras de Aspersão.
        /// </summary>
        public static string Menu_SprayChambers {
            get {
                return ResourceManager.GetString("Menu_SprayChambers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Balanças.
        /// </summary>
        public static string Menu_WeighingScales {
            get {
                return ResourceManager.GetString("Menu_WeighingScales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A câmara selecionada não possui estoque..
        /// </summary>
        public static string Msg_ChamberNoStock {
            get {
                return ResourceManager.GetString("Msg_ChamberNoStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Configuração do simulador salva com sucesso!.
        /// </summary>
        public static string Msg_ConfigSaved {
            get {
                return ResourceManager.GetString("Msg_ConfigSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Isso limpará todos os dados de simulação (notas) e reverterá os estoques das câmaras para o estado inicial. Continuar?.
        /// </summary>
        public static string Msg_ConfirmClearSimulation {
            get {
                return ResourceManager.GetString("Msg_ConfirmClearSimulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tem certeza de que deseja excluir este registro?.
        /// </summary>
        public static string Msg_ConfirmDelete {
            get {
                return ResourceManager.GetString("Msg_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registro excluído com sucesso!.
        /// </summary>
        public static string Msg_DeleteSuccess {
            get {
                return ResourceManager.GetString("Msg_DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Idioma alterado! Reinicie o aplicativo para aplicar as mudanças..
        /// </summary>
        public static string Msg_LanguageChanged {
            get {
                return ResourceManager.GetString("Msg_LanguageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhuma câmara com estoque disponível..
        /// </summary>
        public static string Msg_NoChambersWithStock {
            get {
                return ResourceManager.GetString("Msg_NoChambersWithStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhuma ordem de entrada encontrada para esta câmara..
        /// </summary>
        public static string Msg_NoEntranceOrders {
            get {
                return ResourceManager.GetString("Msg_NoEntranceOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhuma ordem de produção finalizada disponível..
        /// </summary>
        public static string Msg_NoFinalizedOrders {
            get {
                return ResourceManager.GetString("Msg_NoFinalizedOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Esta ordem não possui notas..
        /// </summary>
        public static string Msg_OrderNoNotes {
            get {
                return ResourceManager.GetString("Msg_OrderNoNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registro salvo com sucesso!.
        /// </summary>
        public static string Msg_SaveSuccess {
            get {
                return ResourceManager.GetString("Msg_SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Por favor, selecione uma câmara de aspersão..
        /// </summary>
        public static string Msg_SelectChamber {
            get {
                return ResourceManager.GetString("Msg_SelectChamber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Por favor, selecione uma ordem de produção..
        /// </summary>
        public static string Msg_SelectOrder {
            get {
                return ResourceManager.GetString("Msg_SelectOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Por favor, selecione um registro..
        /// </summary>
        public static string Msg_SelectRecord {
            get {
                return ResourceManager.GetString("Msg_SelectRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dados de simulação limpos com sucesso!.
        /// </summary>
        public static string Msg_SimulationCleared {
            get {
                return ResourceManager.GetString("Msg_SimulationCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Simulação concluída! Todos os registros configurados foram gerados..
        /// </summary>
        public static string Msg_SimulationCompleted {
            get {
                return ResourceManager.GetString("Msg_SimulationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Relatório de Estoque da Câmara.
        /// </summary>
        public static string Report_ChamberStockTitle {
            get {
                return ResourceManager.GetString("Report_ChamberStockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Relatório de Ordem de Produção.
        /// </summary>
        public static string Report_ProductionOrderTitle {
            get {
                return ResourceManager.GetString("Report_ProductionOrderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Total de Itens: {0} | Peso Total: {1} kg | Estoque da Câmara: {2}.
        /// </summary>
        public static string Report_Summary {
            get {
                return ResourceManager.GetString("Report_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Carregando....
        /// </summary>
        public static string Status_Loading {
            get {
                return ResourceManager.GetString("Status_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Abrindo....
        /// </summary>
        public static string Status_Opening {
            get {
                return ResourceManager.GetString("Status_Opening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pronto.
        /// </summary>
        public static string Status_Ready {
            get {
                return ResourceManager.GetString("Status_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Salvando....
        /// </summary>
        public static string Status_Saving {
            get {
                return ResourceManager.GetString("Status_Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Por favor, insira um número válido..
        /// </summary>
        public static string Validation_InvalidNumber {
            get {
                return ResourceManager.GetString("Validation_InvalidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Por favor, carregue uma ordem de produção primeiro..
        /// </summary>
        public static string Validation_LoadOrderFirst {
            get {
                return ResourceManager.GetString("Validation_LoadOrderFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O limite inferior deve ser menor que o limite superior..
        /// </summary>
        public static string Validation_LowerGreaterUpper {
            get {
                return ResourceManager.GetString("Validation_LowerGreaterUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Por favor, preencha todos os campos obrigatórios..
        /// </summary>
        public static string Validation_RequiredField {
            get {
                return ResourceManager.GetString("Validation_RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Por favor, selecione pelo menos uma classificação..
        /// </summary>
        public static string Validation_SelectClassification {
            get {
                return ResourceManager.GetString("Validation_SelectClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Relatório de Estoque da Câmara - Itens em Estoque.
        /// </summary>
        public static string Window_ChamberStockReport {
            get {
                return ResourceManager.GetString("Window_ChamberStockReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Classificações de Pesagem.
        /// </summary>
        public static string Window_Classification {
            get {
                return ResourceManager.GetString("Window_Classification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Editar Câmara.
        /// </summary>
        public static string Window_EditChamber {
            get {
                return ResourceManager.GetString("Window_EditChamber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Editar Classificação.
        /// </summary>
        public static string Window_EditClassification {
            get {
                return ResourceManager.GetString("Window_EditClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Editar Ordem de Produção.
        /// </summary>
        public static string Window_EditOrder {
            get {
                return ResourceManager.GetString("Window_EditOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Editar Item da Ordem.
        /// </summary>
        public static string Window_EditOrderItem {
            get {
                return ResourceManager.GetString("Window_EditOrderItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Editar Produto.
        /// </summary>
        public static string Window_EditProduct {
            get {
                return ResourceManager.GetString("Window_EditProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nova Câmara.
        /// </summary>
        public static string Window_NewChamber {
            get {
                return ResourceManager.GetString("Window_NewChamber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nova Classificação.
        /// </summary>
        public static string Window_NewClassification {
            get {
                return ResourceManager.GetString("Window_NewClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nova Ordem de Produção.
        /// </summary>
        public static string Window_NewOrder {
            get {
                return ResourceManager.GetString("Window_NewOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Novo Item da Ordem.
        /// </summary>
        public static string Window_NewOrderItem {
            get {
                return ResourceManager.GetString("Window_NewOrderItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Novo Produto.
        /// </summary>
        public static string Window_NewProduct {
            get {
                return ResourceManager.GetString("Window_NewProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Produtos.
        /// </summary>
        public static string Window_Product {
            get {
                return ResourceManager.GetString("Window_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ordens de Produção.
        /// </summary>
        public static string Window_ProductionOrder {
            get {
                return ResourceManager.GetString("Window_ProductionOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Relatório de Ordem de Produção - Notas por Câmara.
        /// </summary>
        public static string Window_ProductionOrderReport {
            get {
                return ResourceManager.GetString("Window_ProductionOrderReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Simulador de Ordem de Produção.
        /// </summary>
        public static string Window_Simulator {
            get {
                return ResourceManager.GetString("Window_Simulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Câmaras de Aspersão.
        /// </summary>
        public static string Window_SprayChamber {
            get {
                return ResourceManager.GetString("Window_SprayChamber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Balanças.
        /// </summary>
        public static string Window_WeighingScale {
            get {
                return ResourceManager.GetString("Window_WeighingScale", resourceCulture);
            }
        }
    }
}
